version: '3'

services:
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./local.crt:/certs/local.crt
      - ./local.key:/certs/local.key
      - ./Caddyfile:/etc/caddy/Caddyfile